from __future__ import annotations

import pytest

from tcl_lathe_hmi.cam import (
    CamGenerationError,
    CamValidationError,
    HoleSpec,
    LatheCamJob,
    StockSpec,
    TaperSpec,
    ThreadSpec,
    TurningSpec,
    build_part_outline,
    build_part_mesh,
    generate_cam_program,
)
from tcl_lathe_hmi.cam.generator import _liblathe_commands_to_gcode
from tcl_lathe_hmi.cam.models import finished_profile_points
from tcl_lathe_hmi.gcode import MoveAction, ThreadSyncAction, parse_gcode


class FakeCommand:
    def __init__(self, movement: str, params: dict[str, float] | None = None):
        self.movement = movement
        self.params = params or {}

    def get_movement(self):
        return self.movement

    def getParams(self):
        return self.params


def test_cam_validation_rejects_bore_smaller_than_drill():
    job = LatheCamJob(
        hole=HoleSpec(
            drill=True,
            bore=True,
            drill_diameter_mm=8.0,
            bore_diameter_mm=7.0,
        )
    )

    with pytest.raises(CamValidationError, match="bore diameter"):
        job.validate()


def test_finished_profile_uses_display_diameter_coordinates():
    job = LatheCamJob(
        stock=StockSpec(diameter_mm=20.0, length_mm=60.0),
        turning=TurningSpec(enabled=True, target_diameter_mm=16.0, target_length_mm=50.0),
    )

    assert finished_profile_points(job) == [
        (0.0, 0.0),
        (16.0, 0.0),
        (16.0, -50.0),
        (0.0, -50.0),
    ]


def test_taper_profile_points_are_inside_turned_length():
    job = LatheCamJob(
        stock=StockSpec(diameter_mm=20.0, length_mm=60.0),
        turning=TurningSpec(enabled=True, target_diameter_mm=16.0, target_length_mm=60.0),
        taper=TaperSpec(
            enabled=True,
            start_diameter_mm=16.0,
            end_diameter_mm=12.0,
            start_z_mm=-10.0,
            end_z_mm=-40.0,
        ),
    )

    job.validate()

    assert finished_profile_points(job) == [
        (0.0, 0.0),
        (16.0, 0.0),
        (16.0, -10.0),
        (12.0, -40.0),
        (12.0, -60.0),
        (0.0, -60.0),
    ]


def test_part_outline_includes_bore_boundary():
    outline = build_part_outline(
        LatheCamJob(
            hole=HoleSpec(
                drill=True,
                bore=True,
                drill_diameter_mm=6.0,
                bore_diameter_mm=10.0,
                bore_depth_mm=25.0,
            )
        )
    )

    hole_segments = [segment for segment in outline if segment.mode == "hole"]

    assert len(hole_segments) == 2
    assert hole_segments[0].start_x_mm == 10.0
    assert hole_segments[0].end_z_mm == -25.0


def test_build_part_mesh_uses_stock_length_and_bore_radius():
    mesh = build_part_mesh(
        LatheCamJob(
            stock=StockSpec(diameter_mm=20.0, length_mm=70.0),
            turning=TurningSpec(enabled=True, target_diameter_mm=16.0, target_length_mm=50.0),
            hole=HoleSpec(
                drill=True,
                bore=True,
                drill_diameter_mm=6.0,
                drill_depth_mm=40.0,
                bore_diameter_mm=10.0,
                bore_depth_mm=25.0,
            ),
        ),
        sections=24,
    )

    assert len(mesh.vertices) > 0
    assert len(mesh.faces) > 0
    assert mesh.bounds[0][0] == pytest.approx(-70.0)
    assert mesh.bounds[1][0] == pytest.approx(0.0)
    assert mesh.bounds[0][1] == pytest.approx(-10.0)
    assert mesh.bounds[1][1] == pytest.approx(10.0)


def test_liblathe_command_conversion_doubles_radius_x_and_linearizes_arcs():
    gcode = _liblathe_commands_to_gcode(
        [
            FakeCommand("G0", {"X": 10.0, "Z": 0.0}),
            FakeCommand("G3", {"X": 0.0, "Z": 10.0, "I": -10.0, "K": 0.0, "F": 40.0}),
        ]
    )

    assert gcode[0] == "G0 X20 Z0"
    assert len(gcode) > 2
    assert gcode[-1].startswith("G1 X0 Z10")


def test_default_cam_job_has_no_operations_enabled():
    job = LatheCamJob()

    assert not job.turning.enabled
    assert not job.hole.center_drill
    assert not job.hole.drill
    assert not job.hole.bore
    assert not job.thread.enabled

    program = generate_cam_program(job)

    assert "M06" not in program.gcode
    assert "G33" not in program.gcode
    assert program.gcode == "(Generated by TCL Lathe HMI CAM)\nG21 G90 G18\nM5\n"


def test_generate_cam_program_parses_when_liblathe_is_available():
    try:
        program = generate_cam_program(
            LatheCamJob(
                turning=TurningSpec(enabled=True, face=True, rough=True, finish=True),
            )
        )
    except CamGenerationError as exc:
        pytest.skip(str(exc))

    assert "M06 I1 K1" in program.gcode
    assert "M5" in program.gcode
    assert program.part_outline

    parsed = parse_gcode(program.gcode)
    moves = [action for action in parsed.actions if isinstance(action, MoveAction)]
    assert moves
    assert max(action.target_x_mm for action in moves) > 20.0


def test_part_outline_includes_metric_thread_teeth():
    outline = build_part_outline(
        LatheCamJob(
            thread=ThreadSpec(
                external=True,
                major_diameter_mm=16.0,
                pitch_mm=1.5,
                length_mm=12.0,
                depth_mm=1.2,
            )
        )
    )

    thread_segments = [segment for segment in outline if segment.mode == "thread"]

    assert len(thread_segments) == 16
    assert thread_segments[0].start_x_mm == pytest.approx(16.0)
    assert thread_segments[0].end_x_mm == pytest.approx(14.8)
    assert thread_segments[-1].end_z_mm == pytest.approx(-12.0)


def test_thread_cam_generates_g33_passes_and_retracts():
    program = generate_cam_program(
        LatheCamJob(
            turning=TurningSpec(enabled=False),
            hole=HoleSpec(center_drill=False, drill=False, bore=False),
            thread=ThreadSpec(
                external=True,
                major_diameter_mm=16.0,
                pitch_mm=1.5,
                length_mm=12.0,
                depth_mm=1.2,
                passes=4,
                spring_passes=1,
                start_z_mm=0.0,
                clearance_mm=2.0,
                tool_number=6,
                station=6,
            ),
        )
    )

    assert "M06 I6 K6" in program.gcode
    assert "S300 M3" in program.gcode
    assert program.gcode.count("G33 Z-12 K1.5") == 5
    assert "G0 X20 Z0" in program.gcode
    assert "G0 X14.8 Z0" in program.gcode

    parsed = parse_gcode(program.gcode)
    thread_actions = [action for action in parsed.actions if isinstance(action, ThreadSyncAction)]

    assert len(thread_actions) == 5
    assert all(action.pitch_mm == pytest.approx(1.5) for action in thread_actions)
    assert thread_actions[-1].target_z_mm == pytest.approx(-12.0)


def test_thread_validation_rejects_impossible_depth():
    with pytest.raises(CamValidationError, match="thread depth"):
        LatheCamJob(
            thread=ThreadSpec(
                external=True,
                major_diameter_mm=1.0,
                depth_mm=1.0,
            )
        ).validate()


def test_thread_validation_rejects_unavailable_thread_modes():
    with pytest.raises(CamValidationError, match="internal threading"):
        LatheCamJob(thread=ThreadSpec(internal=True)).validate()
    with pytest.raises(CamValidationError, match="taper threading"):
        LatheCamJob(thread=ThreadSpec(taper=True)).validate()
