from __future__ import annotations

import contextlib
import io
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tcl_lathe_hmi.gcode import PreviewSegment

from .models import LatheCamJob, finished_profile_points


class CamGenerationError(RuntimeError):
    pass


@dataclass(frozen=True)
class GeneratedCamProgram:
    gcode: str
    part_outline: list[PreviewSegment]


def generate_cam_program(job: LatheCamJob) -> GeneratedCamProgram:
    job.validate()
    lines: list[str] = ["(Generated by TCL Lathe HMI CAM)", "G21 G90 G18"]

    if job.turning.enabled and (job.turning.face or job.turning.rough or job.turning.finish):
        lines.extend(_turning_program(job))

    lines.extend(_hole_program(job))
    lines.extend(["M5", ""])
    return GeneratedCamProgram(
        gcode="\n".join(lines),
        part_outline=build_part_outline(job),
    )


def _turning_program(job: LatheCamJob) -> list[str]:
    ll = _load_liblathe()
    tool = ll.Tool()
    try:
        tool.set_tool_from_string(job.turning.tool_string)
        if job.turning.tool_rotation_deg:
            tool.set_rotation(job.turning.tool_rotation_deg)
    except Exception as exc:
        raise CamGenerationError(f"turning tool setup failed: {exc}") from exc

    part_segments = _liblathe_part_segments(job, ll.Point, ll.Segment)
    stock = ll.BoundBox(
        ll.Point(0.0, job.stock.z_front_mm - job.turning.target_length_mm),
        ll.Point(
            job.stock.diameter_mm / 2.0,
            job.stock.z_front_mm + job.stock.face_allowance_mm,
        ),
    )

    lines = [
        "(Turning)",
        _tool_change_line(job.turning.tool_number, job.turning.station),
        f"S{_fmt(job.turning.spindle_rpm)} M3",
    ]

    common_params = {
        "allow_grooving": True,
        "step_over": job.turning.step_over_mm,
        "hfeed": job.turning.rough_feed,
        "vfeed": job.turning.rough_feed,
        "clearance": job.stock.clearance_mm,
    }
    if job.turning.face:
        face_params = {
            **common_params,
            "stock_to_leave": 0.0,
            "finish_passes": 0,
            "hfeed": job.turning.rough_feed,
            "vfeed": job.turning.rough_feed,
        }
        lines.extend(_run_liblathe_op(ll.FaceOP, face_params, stock, part_segments, tool))

    if job.turning.rough:
        rough_params = {
            **common_params,
            "stock_to_leave": job.turning.stock_to_leave_mm / 2.0,
            "finish_passes": 0,
            "hfeed": job.turning.rough_feed,
            "vfeed": job.turning.rough_feed,
        }
        lines.extend(_run_liblathe_op(ll.RoughOP, rough_params, stock, part_segments, tool))

    if job.turning.finish:
        finish_params = {
            **common_params,
            "stock_to_leave": 0.0,
            "finish_passes": 1,
            "hfeed": job.turning.finish_feed,
            "vfeed": job.turning.finish_feed,
        }
        lines.extend(_run_liblathe_op(ll.ProfileOP, finish_params, stock, part_segments, tool))

    clearance_x = job.stock.diameter_mm + job.stock.clearance_mm * 2.0
    clearance_z = job.stock.z_front_mm + job.stock.clearance_mm
    lines.append(f"G0 X{_fmt(clearance_x)} Z{_fmt(clearance_z)}")
    return lines


def _hole_program(job: LatheCamJob) -> list[str]:
    lines: list[str] = []
    front = job.stock.z_front_mm
    safe_z = front + job.stock.clearance_mm

    if job.hole.center_drill:
        lines.extend(
            [
                "(Center drill)",
                _tool_change_line(job.hole.center_tool_number, job.hole.center_station),
                f"S{_fmt(job.hole.spindle_rpm)} M3",
                f"G0 X0 Z{_fmt(safe_z)}",
                f"G1 Z{_fmt(front - job.hole.center_depth_mm)} F{_fmt(job.hole.center_feed)}",
                f"G0 Z{_fmt(safe_z)}",
            ]
        )

    if job.hole.drill:
        lines.extend(
            [
                "(Drill)",
                _tool_change_line(job.hole.drill_tool_number, job.hole.drill_station),
                f"S{_fmt(job.hole.spindle_rpm)} M3",
                f"G0 X0 Z{_fmt(safe_z)}",
                f"G1 Z{_fmt(front - job.hole.drill_depth_mm)} F{_fmt(job.hole.drill_feed)}",
                f"G0 Z{_fmt(safe_z)}",
            ]
        )

    if job.hole.bore:
        lines.extend(
            [
                "(Bore)",
                _tool_change_line(job.hole.boring_tool_number, job.hole.boring_station),
                f"S{_fmt(job.hole.spindle_rpm)} M3",
            ]
        )
        current_diameter = job.hole.drill_diameter_mm
        while current_diameter < job.hole.bore_diameter_mm:
            current_diameter = min(
                job.hole.bore_diameter_mm,
                current_diameter + job.hole.boring_step_over_mm,
            )
            retract_diameter = max(0.0, current_diameter - min(0.5, job.hole.boring_step_over_mm))
            lines.extend(
                [
                    f"G0 X{_fmt(current_diameter)} Z{_fmt(safe_z)}",
                    f"G1 Z{_fmt(front - job.hole.bore_depth_mm)} F{_fmt(job.hole.boring_feed)}",
                    f"G0 X{_fmt(retract_diameter)}",
                    f"G0 Z{_fmt(safe_z)}",
                ]
            )

    return lines


def _run_liblathe_op(
    op_cls,
    params: dict[str, float | bool],
    stock,
    part_segments,
    tool,
) -> list[str]:
    op = op_cls()
    try:
        op.setParams(params)
        op.add_stock(stock)
        op.addPartSegments(part_segments)
        op.add_tool(tool)
        with contextlib.redirect_stdout(io.StringIO()):
            commands = op.getGCode()
    except Exception as exc:
        raise CamGenerationError(f"{op_cls.__name__} failed: {exc}") from exc
    return _liblathe_commands_to_gcode(commands)


def _liblathe_commands_to_gcode(commands: list[Any]) -> list[str]:
    lines: list[str] = []
    current_x: float | None = None
    current_z: float | None = None
    modal_feed: float | None = None

    for command in commands:
        movement = command.get_movement()
        params = dict(command.getParams())
        if "F" in params:
            modal_feed = float(params["F"])

        if movement in {"G2", "G3"} and current_x is not None and current_z is not None:
            target_x = float(params.get("X", current_x))
            target_z = float(params.get("Z", current_z))
            center_x = current_x + float(params.get("I", 0.0))
            center_z = current_z + float(params.get("K", 0.0))
            for point_x, point_z in _linearized_radius_arc(
                current_x,
                current_z,
                target_x,
                target_z,
                center_x,
                center_z,
                clockwise=movement == "G2",
            ):
                line_params = {"X": point_x * 2.0, "Z": point_z}
                if modal_feed is not None:
                    line_params["F"] = modal_feed
                lines.append(_gcode_line("G1", line_params))
            current_x = target_x
            current_z = target_z
            continue

        line_params: dict[str, float] = {}
        for key, value in params.items():
            if key == "X":
                line_params[key] = float(value) * 2.0
            elif key in {"Z", "F"}:
                line_params[key] = float(value)
            elif key == "I":
                line_params[key] = float(value) * 2.0
            elif key == "K":
                line_params[key] = float(value)

        lines.append(_gcode_line(movement, line_params))
        if "X" in params:
            current_x = float(params["X"])
        if "Z" in params:
            current_z = float(params["Z"])

    return lines


def _linearized_radius_arc(
    start_x: float,
    start_z: float,
    target_x: float,
    target_z: float,
    center_x: float,
    center_z: float,
    *,
    clockwise: bool,
) -> list[tuple[float, float]]:
    radius = math.hypot(start_x - center_x, start_z - center_z)
    if radius <= 1e-9:
        return [(target_x, target_z)]
    start_angle = math.atan2(start_z - center_z, start_x - center_x)
    end_angle = math.atan2(target_z - center_z, target_x - center_x)
    if clockwise:
        if end_angle >= start_angle:
            end_angle -= math.tau
    elif end_angle <= start_angle:
        end_angle += math.tau

    sweep = end_angle - start_angle
    steps = max(1, min(180, math.ceil(abs(sweep) * radius / 0.25)))
    return [
        (
            center_x + math.cos(start_angle + sweep * (index / steps)) * radius,
            center_z + math.sin(start_angle + sweep * (index / steps)) * radius,
        )
        for index in range(1, steps + 1)
    ]


def _liblathe_part_segments(job: LatheCamJob, point_cls, segment_cls) -> list[Any]:
    points = finished_profile_points(job)
    radius_points = [(diameter / 2.0, z) for diameter, z in points]
    return [
        segment_cls(point_cls(start_x, start_z), point_cls(end_x, end_z))
        for (start_x, start_z), (end_x, end_z) in zip(radius_points, radius_points[1:])
    ]


def build_part_outline(job: LatheCamJob) -> list[PreviewSegment]:
    points = finished_profile_points(job)
    segments = [
        PreviewSegment(
            start_x_mm=start_x,
            start_z_mm=start_z,
            end_x_mm=end_x,
            end_z_mm=end_z,
            mode="part",
            line_number=0,
        )
        for (start_x, start_z), (end_x, end_z) in zip(points, points[1:])
    ]
    hole_diameter = 0.0
    hole_depth = 0.0
    if job.hole.bore:
        hole_diameter = job.hole.bore_diameter_mm
        hole_depth = job.hole.bore_depth_mm
    elif job.hole.drill:
        hole_diameter = job.hole.drill_diameter_mm
        hole_depth = job.hole.drill_depth_mm

    if hole_diameter > 0.0 and hole_depth > 0.0:
        front = job.stock.z_front_mm
        back = front - hole_depth
        segments.extend(
            [
                PreviewSegment(
                    start_x_mm=hole_diameter,
                    start_z_mm=front,
                    end_x_mm=hole_diameter,
                    end_z_mm=back,
                    mode="hole",
                    line_number=0,
                ),
                PreviewSegment(
                    start_x_mm=0.0,
                    start_z_mm=back,
                    end_x_mm=hole_diameter,
                    end_z_mm=back,
                    mode="hole",
                    line_number=0,
                ),
            ]
        )
    return segments


def _tool_change_line(tool_number: int, station: int | None) -> str:
    line = f"M06 I{tool_number}"
    if station is not None:
        line += f" K{station}"
    return line


def _gcode_line(movement: str, params: dict[str, float]) -> str:
    if not params:
        return movement
    return movement + " " + " ".join(f"{key}{_fmt(value)}" for key, value in params.items())


def _fmt(value: float) -> str:
    if abs(value) < 0.0005:
        value = 0.0
    return f"{value:.3f}".rstrip("0").rstrip(".")


@dataclass(frozen=True)
class _LibLatheModules:
    Point: Any
    BoundBox: Any
    Segment: Any
    FaceOP: Any
    RoughOP: Any
    ProfileOP: Any
    Tool: Any


def _load_liblathe() -> _LibLatheModules:
    repo_root = Path(__file__).resolve().parents[2]
    vendor_path = repo_root / "vendor" / "LibLathe"
    if vendor_path.exists():
        vendor_text = str(vendor_path)
        if vendor_text not in sys.path:
            sys.path.insert(0, vendor_text)
    try:
        from liblathe.base.boundbox import BoundBox
        from liblathe.base.point import Point
        from liblathe.base.segment import Segment
        from liblathe.op.face import FaceOP
        from liblathe.op.profile import ProfileOP
        from liblathe.op.rough import RoughOP
        from liblathe.tool.tool import Tool
    except Exception as exc:
        raise CamGenerationError(
            "LibLathe is not importable. Initialize the submodule and run "
            "`python -m pip install -e vendor/LibLathe` in the HMI environment."
        ) from exc
    return _LibLatheModules(
        Point=Point,
        BoundBox=BoundBox,
        Segment=Segment,
        FaceOP=FaceOP,
        RoughOP=RoughOP,
        ProfileOP=ProfileOP,
        Tool=Tool,
    )
